---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true

---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
library(echarts4r)
```



# 引言
此页面正在测试中！

```{r}
data <- data.frame(
  month = paste0(c(1:12), "月"),
  Evaporation = sample(2:200, 12),
  Precipitation = sample(2:200, 12),
  Temperature = sample(2:25, 12, replace = TRUE)
)
```
# 形式一
```{r}
e_charts(data, month) |> # 横轴
  e_bar(Evaporation) # 纵轴
```
# 形式二
```{R}
data.waterfall <- data.frame(
  date = paste0("Nov", c(1:11)),
  transparent = c(0, 900, 1245, 1530, 1376, 1376, 1511, 1689, 1856, 1495, 1292), # 总和
  positive = c(900, 345, 393, "-", "-", 135, 178, 286, "-", "-", "-"), # 正数
  negative = c("-", "-", "-", 108, 154, "-", "-", "-", 119, 361, 203)
) # 负数

data.waterfall |>
  e_charts(date) |>
  e_bar(
    transparent,
    stack = "total",
    name = "总和",
    itemStyle = list(borderColor = "transparent", color = "transparent"), # 将柱子和描边的颜色都设为透明
    legend = list(show = FALSE), # 去掉总和的图例
    tooltip = list(show = FALSE)
  ) |>
  e_bar(positive, stack = "total", name = "收入") |>
  e_bar(negative, stack = "total", name = "支出") |>
  e_x_axis(type = "category", axisLabel = list(interval = 0)) |>
  e_tooltip(
    trigger = "axis",
    axisPointer = list(type = "shadow")
  )
```
# 形式三
```{r}
cns <- countrycode::codelist$country.name.en
cns <- data.frame(
  country = cns,
  value = runif(length(cns), 1, 100)
)

cns |>
  e_charts(country) |> # 国家
  e_map(value) |>
  e_visual_map(value)
```
# 形式四
```{r}
data |>
  e_charts(month) |>
  e_polar() |>
  e_angle_axis() |>
  e_radius_axis(month, axisLabel = list(interval = 0)) |>
  e_bar(Evaporation,
    name = "蒸发量",
    coord_system = "polar",
    stack = "堆一堆"
  ) |>
  e_bar(
    Precipitation,
    name = "降水量",
    coord_system = "polar",
    stack = "堆一堆"
  )
```