---
title: "张方方毕设的数据分析"
author: "张方方"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
---


# 数据导入

## 预处理

选取了无数据空缺的年份；即2002~2017年。

```{r warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(xlsx)
library(showtext)
mydataframe <- read.xlsx('FangFang.xlsx', 1)
```

# 数据分析

## 计算协方差矩阵

```{R warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
MDFcov <- cov(mydataframe[-1])
MDFcov
```

## 转换为相关系数矩阵

```{r warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
MDFcor <- cov2cor(MDFcov)
MDFcor
```

## 判断需要提取的公共因子数

```{r warning=FALSE,dev='svg'}
knitr::opts_chunk$set(echo = FALSE)
library(psych)
fa.parallel(MDFcor, n.obs=18, fa="both", n.iter=300,
            main="Scree plots with parallel analysis")
```

因子图形同时展示主成分和公共因子分析的结果。

## 提取公共因子

设定旋转的方法为互变异数最小法;提取公共因子的方法为主轴迭代法（pa ）。

```{r warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
fa(MDFcor, nfactors=2, n.obs=18, rotate="none", scores = T, fm='pa')
fa(MDFcor, nfactors=4, n.obs=18, rotate="none", scores = T, fm='pa')
```

可以看出两个因子解释了十八个观测值的86%的方差；
而四个因子解释了十八个观测值的96%的方差。

## 提取因子

### 用正交旋转提取因子

#### 当n=2时

```{r warning=TRUE}
knitr::opts_chunk$set(echo = FALSE)
MDFvarimax2 <- fa(MDFcor, nfactors=2, rotate="varimax", fm="pa")
MDFvarimax2
```

#### 当n=4时

```{r warning=TRUE}
MDFvarimax4 <- fa(MDFcor, nfactors=4, rotate="varimax", fm="pa")
MDFvarimax4
```

### 用斜交旋转提取因子

#### 当n=2时

```{r warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
MDFpromax2 <- fa(MDFcor, nfactors=2, rotate="promax", fm="pa")
MDFpromax2
```

#### 当n=4时

```{r warning=TRUE}
MDFpromax4 <- fa(MDFcor, nfactors=4, rotate="promax", fm="pa")
MDFpromax4
```

## 计算因子载荷矩阵

创建了一个函数用来计算因子载荷矩阵。

```{r echo=FALSE, fig.height=10, fig.showtext=TRUE, fig.width=10, warning=FALSE, dev='svg'}
# knitr::opts_chunk$set(echo = FALSE)
fsm2 <- function(oblique) {
if (class(oblique)[2]=="fa" & is.null(oblique$Phi)) {
    warning("Object doesn't look like oblique EFA")
} else {
    P <- unclass(oblique$loading)
    F <- P %*% oblique$Phi
    colnames(F) <- c("PA1", "PA2")
    return(F)
}
}

fsm4 <- function(oblique) {
if (class(oblique)[2]=="fa" & is.null(oblique$Phi)) {
    warning("Object doesn't look like oblique EFA")
} else {
    P <- unclass(oblique$loading)
    F <- P %*% oblique$Phi
    colnames(F) <- c("PA1", "PA2","PA3","PA4")
    return(F)
}
}
```

#### 当n=2时

```{r warning=TRUE,dev='svg', fig.showtext=TRUE}
fsm2(MDFpromax2)
factor.plot(MDFpromax2, labels=rownames(MDFvarimax2$loadings), pos = 1, 
            xlim = c(-1.3,1.3),ylim = c(-1,1), pin = c(10,8), cex=0.6, 
            show.points = F)
```

#### 当n=4时

```{r warning=TRUE,dev='svg', fig.showtext=TRUE}
fsm4(MDFpromax4)
factor.plot(MDFpromax4, labels=rownames(MDFvarimax4$loadings), pos = 1, 
            xlim = c(-1.3,1.3),ylim = c(-1,1), pin = c(10,8), cex=0.6, 
            show.points = F)
```
```{r echo=FALSE, fig.showtext=TRUE, fig.width=10, warning=FALSE, dev='svg'}
# knitr::opts_chunk$set(echo = FALSE)
fa.diagram(MDFpromax2, simple = F, rsize = 1.3)
fa.diagram(MDFpromax4, simple=F, rsize = 1.3)
MDFpromax2$weights # 因子得分
MDFpromax4$weights
```